-- H2 in-memory test schema. Must be kept in sync with supabase/migrations/ when tables change.
-- Uses GENERATED BY DEFAULT AS IDENTITY instead of PostgreSQL sequences (H2 equivalent).

CREATE SCHEMA IF NOT EXISTS "public";
SET SCHEMA "public";

CREATE TABLE IF NOT EXISTS "suite_user" (
    "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid"    TEXT   NOT NULL,
    "email"   TEXT
);

ALTER TABLE "suite_user" ADD CONSTRAINT IF NOT EXISTS "suite_user_uuid_unique" UNIQUE ("uuid");

MERGE INTO "suite_user" USING (VALUES ('Guest')) AS v("uuid") ON "suite_user"."uuid" = v."uuid" WHEN NOT MATCHED THEN INSERT ("uuid") VALUES ('Guest');

CREATE TABLE IF NOT EXISTS "conversation" (
    "conversation_id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"           BIGINT                   NOT NULL,
    "conversation_name" TEXT                     NOT NULL,
    "create_time"       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "root_directory"    TEXT,
    "external_id"       TEXT                     NOT NULL DEFAULT RANDOM_UUID() UNIQUE,
    CONSTRAINT "fk_conversation_user" FOREIGN KEY ("user_id") REFERENCES "suite_user" ("user_id")
);

CREATE TABLE IF NOT EXISTS "message" (
    "message_id"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"         BIGINT                   NOT NULL,
    "conversation_id" BIGINT                   NOT NULL,
    "type"            TEXT                     NOT NULL,
    "message"         TEXT                     NOT NULL,
    "message_time"    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT "fk_message_user" FOREIGN KEY ("user_id") REFERENCES "suite_user" ("user_id"),
    CONSTRAINT "fk_message_conversation" FOREIGN KEY ("conversation_id") REFERENCES "conversation" ("conversation_id")
);
