ALTER TABLE public.message ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suite_user ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_role ENABLE ROW LEVEL SECURITY;
